version: "3.7"
services:
  prometheus-blackbox-exporter:
    build: .
    image: homecentr/prometheus-blackbox-exporter
    ports:
      - 9115:9115
    volumes:
      - ./example:/config
    restart: unless-stopped